{% set version = "4.0.0" %}

package:
  name: django-recaptcha
  version: {{ version }}

source:
  url: https://github.com/praekelt/django-recaptcha/archive/{{ version }}.tar.gz
  sha256: ae5e7897888b34f7d72186a7a51493ffeb6a31f7be32dd30667acf83c485d185

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - django

test:
  requires:
    - pip
  commands:
    - pip check
    - python -c "import django; from django.conf import settings; settings.configure(); django.setup(); import captcha"

about:
  home: http://github.com/praekelt/django-recaptcha
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Django recaptcha form field/widget app.

extra:
  recipe-maintainers:
    - ocefpaf
