{% set name = "django-recaptcha" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-recaptcha-{{ version }}.tar.gz
  sha256: 253197051288923cae675d7eff91b619e3775311292a5dbaf27a8a55ffebc670

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - django

test:
  requires:
    - pip
  commands:
    - pip check
    - python -c "import django; from django.conf import settings; settings.configure(); django.setup(); import captcha"

about:
  home: https://github.com/torchbox/django-recaptcha
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Django recaptcha form field/widget app.

extra:
  recipe-maintainers:
    - ocefpaf
