{% set name = "django-recaptcha" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-recaptcha-{{ version }}.tar.gz
  sha256: 5316438f97700c431d65351470d1255047e3f2cd9af0f2f13592b637dad9213e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - django

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - python -c "import django; from django.conf import settings; settings.configure(); django.setup(); import django_recaptcha"

about:
  home: https://github.com/torchbox/django-recaptcha
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Django recaptcha form field/widget app.

extra:
  recipe-maintainers:
    - ocefpaf
    - sdc50
